### ISSUE TITLE
大神想请教个问题！

### ISSUE THREAD

**Issue by zr8657** [beijixiaohu/CH9329_COMM#2]
纯新手，这个CH9329模块必须再加一个USB转TTL模块两个一起插在电脑上才行吗？

**Comment by beijixiaohu** [comment]
> 纯新手，这个CH9329模块必须再加一个USB转TTL模块两个一起插在电脑上才行吗？

对的，CH340就行

**Comment by zr8657** [comment]
> > 纯新手，这个CH9329模块必须再加一个USB转TTL模块两个一起插在电脑上才能行吗？
> 
> 对的，CH340就行

谢谢！
